kind: pipeline
name: logstash-docker

steps:
  - name: publish-docker
    image: plugins/gcr
    settings:
      repo: prod-bip/ssb/logstash
      registry: eu.gcr.io
      tags: "${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:8}"
      json_key:
        from_secret: gcr_credentials
    when:
      branch:
        - master
      event:
        - push
---
kind: secret
name: gcr_credentials
get:
  path: drone-gcr-credentials
  name: gcr-credentials
